# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b65fec64c7f63fbc3231e28e36bbf790b52e591cff673e0454f52cf751469dbfabcd13667eb11ce98a647debf5176733d4851f067014c33f71f5c216cf7dc3

test:
  secret_key_base: 7db2c65e404d76749512d175dd275de35ca21470f670f4e3f66e932235140117d1fef45981b016037ac0103acbee8b0bb363619534a971657d487882f3fa67f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
